services:
  redis:
    image: "redis"
    container_name: "LDDJredis"
    ports:
      - "6379:6379"
    volumes:
      - "../data/redis:/data"
    restart: always
  mysql:
    image: "mysql:8.0"
    container_name: "LDDJmysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "LDDJ_CUSTOMER"
      MYSQL_USER: "LDDJ"
      MYSQL_PASSWORD: "LDDJ"
    ports:
      - "3306:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - "../data/mysql:/var/lib/mysql"
      - "../data/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql"
    restart: always
  consul:
    image: "hashicorp/consul"
    container_name: "LDDJconsul"
    ports:
      - "8500:8500"
    command: agent -dev -client=0.0.0.0
    restart: always
  jaeger:
    image: "jaegertracing/all-in-one:latest"
    container_name: "LDDJjaeger"
    ports:
      - "16686:16686"
      - "14268:14268"
      - "14269:14269"
      - "14250:14250"
      - "4317:4317"
      - "4318:4318"
      - "6831:6831"
      - "6832:6832"
      - "9411:9411"
      - "5778:5778"
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: 9411
      COLLECTOR_OTLP_ENABLED: "true"
      # COLLECTOR_OTLP_PROTOCOL: "grpc"
      # COLLECTOR_OTLP_ENDPOINT: "0.0.0.0:4317"
    restart: always
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: "LLDJapp"
  #   ports:
  #     - "8080:8080"
  #   depends_on: ["redis", "mysql"]
  #   environment:
  #     REDIS_HOST: "redis"
  #     MYSQL_HOST: "mysql"
  #     MYSQL_USER: "LLDJ"
  #     MYSQL_PASSWORD: "LLDJ"
  #     MYSQL_DATABASE: "LLDJ"