// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: api/valuation/v1/valuation.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EstimatePriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin      string `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination string `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (x *EstimatePriceRequest) Reset() {
	*x = EstimatePriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_valuation_v1_valuation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstimatePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimatePriceRequest) ProtoMessage() {}

func (x *EstimatePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_valuation_v1_valuation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimatePriceRequest.ProtoReflect.Descriptor instead.
func (*EstimatePriceRequest) Descriptor() ([]byte, []int) {
	return file_api_valuation_v1_valuation_proto_rawDescGZIP(), []int{0}
}

func (x *EstimatePriceRequest) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *EstimatePriceRequest) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type EstimatePriceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code        int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message     string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Origin      string `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	Destination string `protobuf:"bytes,4,opt,name=destination,proto3" json:"destination,omitempty"`
	Price       int32  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *EstimatePriceReply) Reset() {
	*x = EstimatePriceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_valuation_v1_valuation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EstimatePriceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimatePriceReply) ProtoMessage() {}

func (x *EstimatePriceReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_valuation_v1_valuation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimatePriceReply.ProtoReflect.Descriptor instead.
func (*EstimatePriceReply) Descriptor() ([]byte, []int) {
	return file_api_valuation_v1_valuation_proto_rawDescGZIP(), []int{1}
}

func (x *EstimatePriceReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EstimatePriceReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EstimatePriceReply) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *EstimatePriceReply) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

func (x *EstimatePriceReply) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_api_valuation_v1_valuation_proto protoreflect.FileDescriptor

var file_api_valuation_v1_valuation_proto_rawDesc = []byte{
	0x0a, 0x20, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f,
	0x76, 0x31, 0x2f, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x10, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x76, 0x31, 0x22, 0x50, 0x0a, 0x14, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72,
	0x69, 0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x92, 0x01, 0x0a, 0x12, 0x45, 0x73, 0x74, 0x69, 0x6d,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f, 0x72, 0x69,
	0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x32, 0x6d, 0x0a, 0x09, 0x56,
	0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x60, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x45,
	0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x26, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e,
	0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x33, 0x0a, 0x10, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x50, 0x01,
	0x5a, 0x1d, 0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x76, 0x61, 0x6c, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_valuation_v1_valuation_proto_rawDescOnce sync.Once
	file_api_valuation_v1_valuation_proto_rawDescData = file_api_valuation_v1_valuation_proto_rawDesc
)

func file_api_valuation_v1_valuation_proto_rawDescGZIP() []byte {
	file_api_valuation_v1_valuation_proto_rawDescOnce.Do(func() {
		file_api_valuation_v1_valuation_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_valuation_v1_valuation_proto_rawDescData)
	})
	return file_api_valuation_v1_valuation_proto_rawDescData
}

var file_api_valuation_v1_valuation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_valuation_v1_valuation_proto_goTypes = []any{
	(*EstimatePriceRequest)(nil), // 0: api.valuation.v1.EstimatePriceRequest
	(*EstimatePriceReply)(nil),   // 1: api.valuation.v1.EstimatePriceReply
}
var file_api_valuation_v1_valuation_proto_depIdxs = []int32{
	0, // 0: api.valuation.v1.Valuation.GetEstimatePrice:input_type -> api.valuation.v1.EstimatePriceRequest
	1, // 1: api.valuation.v1.Valuation.GetEstimatePrice:output_type -> api.valuation.v1.EstimatePriceReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_valuation_v1_valuation_proto_init() }
func file_api_valuation_v1_valuation_proto_init() {
	if File_api_valuation_v1_valuation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_valuation_v1_valuation_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EstimatePriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_valuation_v1_valuation_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*EstimatePriceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_valuation_v1_valuation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_valuation_v1_valuation_proto_goTypes,
		DependencyIndexes: file_api_valuation_v1_valuation_proto_depIdxs,
		MessageInfos:      file_api_valuation_v1_valuation_proto_msgTypes,
	}.Build()
	File_api_valuation_v1_valuation_proto = out.File
	file_api_valuation_v1_valuation_proto_rawDesc = nil
	file_api_valuation_v1_valuation_proto_goTypes = nil
	file_api_valuation_v1_valuation_proto_depIdxs = nil
}
