server:
  http:
    addr: 0.0.0.0:8004
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9004
    timeout: 1s
data:
  database:
    driver: mysql
    source: LDDJ:LDDJ@tcp(127.0.0.1:3306)/LDDJ_CUSTOMER?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
service:
  consul:
    address: 192.168.86.133:8500
    timeout: 5s 
  jaeger:
    address: http://192.168.86.133:14268/api/traces